### ISSUE TITLE
[FIX] Ceasar Cipher Breaker Spacing issue

### ISSUE THREAD

**Issue by AlexKollar** [AlexKollar/Cryptex#53]
### In a nut shell:
When you go to break a code in Ceasar Cipher using -b the output is correct however, it adds letters where there should be spaces.

**Example**
![image](https://user-images.githubusercontent.com/89718570/169399809-7cfd1b48-6dd8-4bb0-8c2f-d458bc35d684.jpeg)

**_I feel this might also be an issue in the main Ceasar Cipher code as well as it seems to replace spaces with letters._**

### TODO
- [ ] Fix the space replacement in the main code.
- [ ] Make sure it translates into the break function. 
- [ ] > Double check it works in the standard decryption mode as well.
